apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-webapp-w2i-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w2i
  template:
    metadata:
      labels:
        app: w2i
    spec:
      containers:
      - name: w2i-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/gcp-series-week1/flask-webapp-w2i-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"